# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("intro", models.TextField()),
                ("image", models.URLField(max_length=500)),
                ("category", models.CharField(max_length=100)),
                ("link", models.URLField(max_length=500)),
                ("thumbnail", models.URLField(max_length=500)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("portfolio", "Portfolio"), ("design", "Design")],
                        default="portfolio",
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("Mobile", "Mobile"), ("Web", "Web")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("github", models.URLField(blank=True, max_length=500)),
                ("overview_images", models.JSONField(default=list)),
                ("features", models.JSONField(blank=True, default=list, null=True)),
                ("tools", models.JSONField(default=list)),
                ("rnr", models.JSONField(blank=True, default=list, null=True)),
                ("details", models.JSONField(blank=True, default=dict, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
